### PR TITLE
mn-samples-iso updated

### PR DESCRIPTION
**Pull request by Intelligent2013**

### CODE REVIEW

**Comment by Intelligent2013** [comment]
@ronaldtse Could you help, please? XML files from mn-samples-iso didn't processed and there aren't PDF in resulted artifacts. The pipeline doesn't see xml files from mn-samples-iso.

**Comment by Intelligent2013** [comment]
Looks like ISO PDFs didn't created again.

**Comment by Intelligent2013** [comment]
I've understood the reason - in mn-samples-iso\documents\ there are a two sub-folders `amendment` and `international-standard`. I'll try to fix a bit later.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Pull request merged**
