### PR TITLE
Add MN sample sources and Word output for IEC

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
The Word layout looks like this:

Screen Shot 2019-12-28 at 8 58 30 PM
Screen Shot 2019-12-28 at 8 58 48 PM

Located at `reference-docs/iec-rice.doc`.

The IEC PDF looks like this now:
Screen Shot 2019-12-28 at 8 59 30 PM

**Comment by Intelligent2013** [comment]
@ronaldtse Looks like xml and xslt for ISO are using for produce IEC PDF.
In makefile:
looks like instead of 
sources/iec-%.xml: mn-samples-iso/documents/iec-%.xml
should be
sources/iec-%.xml: mn-samples-**iec**/documents/iec-%.xml

And there is an issue when create XSLT_PATH variable. I see the problem in iec-*.xml and iso-*.xml both have root element 'iso-standard' and in the line:
MN_FLAVOR=$$(xmllint --xpath 'name(*)' $${FILENAME} | cut -d '-' -f 1); \
=> iso
DOCTYPE=$$(xmllint --xpath "//*[local-name()='doctype']/text()" $${FILENAME}); \
=> international-standard
XSLT_PATH=${XSLT_PATH_BASE}/$${MN_FLAVOR}.$${DOCTYPE}.xsl; \
=> iso.international-standard.xsl
But should be iec.international-standard.xsl

**Comment by ronaldtse** [comment]
> Looks like xml and xslt for ISO are using for produce IEC PDF. (Makefile)

Fixed.

> And there is an issue when create XSLT_PATH variable. I see the problem in iec-.xml and iso-.xml both have root element 'iso-standard' 

You're right, this is a bug. @opoudjis will get it fixed:

https://github.com/metanorma/metanorma-iec/issues/17

**Comment by ronaldtse** [comment]
@Intelligent2013 there seems to be still an error with IEC generation. Could you help check this?

```sh
file:/Users/me/src/mn/mn-native-pdf/xslt/iec.international-standard.xsl; Line #375; Column #60; org.apache.xml.utils.WrappedRuntimeException: Could not find variable with the name of sectionNum
java.lang.NullPointerException
	at com.metanorma.fop.XML2PDF.convertXML2PDF(XML2PDF.java:62)
	at com.metanorma.fop.XML2PDF.main(XML2PDF.java:148)
make: *** [documents/iec-rice.pdf] Error 255
```

**Comment by Intelligent2013** [comment]
> @Intelligent2013 there seems to be still an error with IEC generation. Could you help check this?

@ronaldtse I've fixed the issue.

**Comment by ronaldtse** [comment]
@Intelligent2013 thanks for fixing the previous problem, there still seems to be one more:

```sh
org.apache.fop.pdf.PDFConformanceException: PDF/UA-1 requires the title to be set.
	at org.apache.fop.pdf.PDFProfile.verifyTitleAbsent(PDFProfile.java:293)
	at org.apache.fop.pdf.PDFInfo.toPDF(PDFInfo.java:224)
```

Full trace when using `make`:

```sh
FILENAME=sources/iec-rice.xml; \
	OUTFILE=documents/iec-rice.pdf; \
	MN_FLAVOR=$(xmllint --xpath 'name(*)' ${FILENAME} | cut -d '-' -f 1); \
	DOCTYPE=$(xmllint --xpath "//*[local-name()='doctype']/text()" ${FILENAME}); \
	XSLT_PATH=/Users/me/src/mn/mn-native-pdf/xslt/${MN_FLAVOR}.${DOCTYPE}.xsl; \
  java -jar mn2pdf.jar pdf_fonts_config.xml $FILENAME $XSLT_PATH $OUTFILE
mn2pdf

Preparing...
Input: FOP config (pdf_fonts_config.xml)
Input: XML (sources/iec-rice.xml)
Input: XSL (/Users/me/src/mn/mn-native-pdf/xslt/iec.international-standard.xsl)
Output: PDF (documents/iec-rice.pdf)

Transforming...
Jan 05, 2020 7:26:04 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Jan 05, 2020 7:26:04 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Jan 05, 2020 7:26:04 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Font "DroidSans,normal,700" not found. Substituting with "DroidSans,normal,400".
Jan 05, 2020 7:26:04 PM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #1.
Jan 05, 2020 7:26:04 PM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #2.
Jan 05, 2020 7:26:04 PM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #3.
org.apache.fop.pdf.PDFConformanceException: PDF/UA-1 requires the title to be set.
	at org.apache.fop.pdf.PDFProfile.verifyTitleAbsent(PDFProfile.java:293)
	at org.apache.fop.pdf.PDFInfo.toPDF(PDFInfo.java:224)
	at org.apache.fop.pdf.FileIDGenerator$DigestFileIDGenerator.generateFileID(FileIDGenerator.java:93)
	at org.apache.fop.pdf.FileIDGenerator$DigestFileIDGenerator.getOriginalFileID(FileIDGenerator.java:77)
	at org.apache.fop.pdf.PDFDocument.createTrailerDictionary(PDFDocument.java:1141)
	at org.apache.fop.pdf.PDFDocument.writeTrailer(PDFDocument.java:1008)
	at org.apache.fop.pdf.PDFLinearization.outputPages(PDFLinearization.java:264)
	at org.apache.fop.render.pdf.PDFContentGenerator.flushPDFDoc(PDFContentGenerator.java:153)
	at org.apache.fop.render.pdf.PDFDocumentHandler.endDocument(PDFDocumentHandler.java:189)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.endDocument(IFDocumentHandlerProxy.java:187)
	at org.apache.fop.render.intermediate.IFRenderer.stopRenderer(IFRenderer.java:295)
	at org.apache.fop.area.RenderPagesModel.endDocument(RenderPagesModel.java:265)
	at org.apache.fop.area.AreaTreeHandler.endDocument(AreaTreeHandler.java:342)
	at org.apache.fop.fo.DelegatingFOEventHandler.endDocument(DelegatingFOEventHandler.java:94)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endDocument(FO2StructureTreeConverter.java:124)
	at org.apache.fop.fo.FOTreeBuilder.endDocument(FOTreeBuilder.java:170)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endDocument(TransformerIdentityImpl.java:963)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:746)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:546)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:93)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:148)
make: *** [documents/iec-rice.pdf] Error 255
```

**Comment by Intelligent2013** [comment]
@ronaldtse Issue fixed.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Confirmed fixed. Merging now.

**Pull request merged**
