### PR TITLE
Issues #169. #167, #170  and IEC xslt fixing

### PR DESCRIPTION
**Pull request by Intelligent2013**

### CODE REVIEW

**Comment by Intelligent2013** [comment]
@ronaldtse How can I fix this issue? 

image

I didn't change anything in makefile:

**Comment by ronaldtse** [comment]
@Intelligent2013 I've updated the code and rebased, hope the issue goes away.

**Comment by ronaldtse** [comment]
I found out that these documents are only partially generated in mn-samples-ogc:

12-077r1.rxl (DOC and HTML missing)
12-077r1.xml
14-065r2.rxl  (DOC and HTML missing)
14-065r2.xml

**Comment by ronaldtse** [comment]
@Intelligent2013 fixed in https://github.com/metanorma/mn-samples-ogc/commit/b0b9bdfdc7b2cca2c156aac9453eb74d3a51ffed , will need to run `make update-modules` after that build is deployed.

**Comment by Intelligent2013** [comment]
Thank you for update.

**Pull request merged**
