### PR TITLE
Namespace changed

### PR DESCRIPTION
**Pull request by Intelligent2013**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@Intelligent2013 is this now mergeable?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is this now mergeable?

No, G.650.1-201803-v2.xml still has namespace 'https://open.ribose.com/standards/itu', instead of 'https://www.metanorma.com/ns/itu'.

**Comment by opoudjis** [comment]
The XML should be periodically regenerated anyway for those samples, since there are updates to the generated XML. In the source samples directories, they are regenerated every time there is a Metanorma gem release (unless docker crashes, which is not infrequently).

**Comment by Intelligent2013** [comment]
@ronaldtse I would like to merge this PR, but can't due - 
https://metanorma.github.io/mn-samples-itu/documents/G.650.1-201803-v2.xml has namespace "https://open.ribose.com/standards/itu" instead of "https://www.metanorma.com/ns/itu". Could you fix it, please?

**Comment by ronaldtse** [comment]
@Intelligent2013 sorry about that -- will fix it in a new ticket, hang on.

**Comment by Intelligent2013** [comment]
@ronaldtse Looks like the namespaces changed again - from ...metanorma.com... to ...metanorma.org... I'll change them in xslts.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by ronaldtse** [comment]
@camobap795 is fixing the ITU document issue and will ping you once he updates the submodule located here.

**Comment by ronaldtse** [comment]
This is fixed, waiting for tests to pass.

**Comment by ronaldtse** [comment]
We have an issue here. Is this the document lacking the title, or an issue with the XSL?

```sh
2020-03-19T03:56:52.1543453Z Preparing...
2020-03-19T03:56:52.1547475Z Input: FOP config (pdf_fonts_config.xml)
2020-03-19T03:56:52.1549618Z Input: XML (sources/itu-G.650.1-201803-v2.xml)
2020-03-19T03:56:52.1551521Z Input: XSL (/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/itu.recommendation.xsl)
2020-03-19T03:56:52.1553956Z Output: PDF (documents/itu-G.650.1-201803-v2.pdf)
2020-03-19T03:56:52.1555487Z 
2020-03-19T03:56:52.1557904Z Transforming...
2020-03-19T03:56:52.9498095Z Mar 19, 2020 3:56:52 AM org.apache.fop.apps.FopConfParser configure
2020-03-19T03:56:52.9499430Z INFO: Default page-height set to: 11.00in
2020-03-19T03:56:52.9507138Z Mar 19, 2020 3:56:52 AM org.apache.fop.apps.FopConfParser configure
2020-03-19T03:56:52.9508304Z INFO: Default page-width set to: 8.50in
2020-03-19T03:56:53.5226567Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.5227819Z INFO: An fo:table  (See position 1:40195) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
2020-03-19T03:56:53.7128741Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7129787Z INFO: Rendered page #1.
2020-03-19T03:56:53.7152956Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7153717Z INFO: Rendered page #2.
2020-03-19T03:56:53.7423955Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7425775Z WARNING: Font "Cambria Math,normal,700" not found. Substituting with "Cambria Math,normal,400".
2020-03-19T03:56:53.7640563Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7641299Z INFO: Rendered page #3.
2020-03-19T03:56:53.7684352Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7686233Z INFO: Rendered page #4.
2020-03-19T03:56:53.7825191Z Mar 19, 2020 3:56:53 AM org.apache.fop.events.LoggingEventListener processEvent
2020-03-19T03:56:53.7825954Z INFO: Rendered page #5.
2020-03-19T03:56:53.8104043Z org.apache.fop.pdf.PDFConformanceException: PDF/UA-1 requires the title to be set.
2020-03-19T03:56:53.8105578Z 	at org.apache.fop.pdf.PDFProfile.verifyTitleAbsent(PDFProfile.java:293)
2020-03-19T03:56:53.8106591Z 	at org.apache.fop.pdf.PDFInfo.toPDF(PDFInfo.java:224)
2020-03-19T03:56:53.8107438Z 	at org.apache.fop.pdf.FileIDGenerator$DigestFileIDGenerator.generateFileID(FileIDGenerator.java:93)
2020-03-19T03:56:53.8108615Z 	at org.apache.fop.pdf.FileIDGenerator$DigestFileIDGenerator.getOriginalFileID(FileIDGenerator.java:77)
2020-03-19T03:56:53.8109570Z 	at org.apache.fop.pdf.PDFDocument.createTrailerDictionary(PDFDocument.java:1141)
2020-03-19T03:56:53.8110444Z 	at org.apache.fop.pdf.PDFDocument.writeTrailer(PDFDocument.java:1008)
2020-03-19T03:56:53.8111359Z 	at org.apache.fop.pdf.PDFLinearization.outputPages(PDFLinearization.java:264)
2020-03-19T03:56:53.8111988Z 	at org.apache.fop.render.pdf.PDFContentGenerator.flushPDFDoc(PDFContentGenerator.java:153)
2020-03-19T03:56:53.8112790Z 	at org.apache.fop.render.pdf.PDFDocumentHandler.endDocument(PDFDocumentHandler.java:189)
2020-03-19T03:56:53.8114251Z 	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.endDocument(IFDocumentHandlerProxy.java:187)
2020-03-19T03:56:53.8115521Z 	at org.apache.fop.render.intermediate.IFRenderer.stopRenderer(IFRenderer.java:295)
2020-03-19T03:56:53.8116367Z 	at org.apache.fop.area.RenderPagesModel.endDocument(RenderPagesModel.java:265)
2020-03-19T03:56:53.8120230Z 	at org.apache.fop.area.AreaTreeHandler.endDocument(AreaTreeHandler.java:342)
2020-03-19T03:56:53.8120643Z 	at org.apache.fop.fo.DelegatingFOEventHandler.endDocument(DelegatingFOEventHandler.java:94)
2020-03-19T03:56:53.8121260Z 	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endDocument(FO2StructureTreeConverter.java:124)
2020-03-19T03:56:53.8121684Z 	at org.apache.fop.fo.FOTreeBuilder.endDocument(FOTreeBuilder.java:170)
2020-03-19T03:56:53.8145202Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.endDocument(TransformerIdentityImpl.java:963)
2020-03-19T03:56:53.8147211Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:745)
2020-03-19T03:56:53.8149609Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
2020-03-19T03:56:53.8153960Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
2020-03-19T03:56:53.8154465Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
2020-03-19T03:56:53.8156289Z 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
2020-03-19T03:56:53.8158111Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
2020-03-19T03:56:53.8159865Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
2020-03-19T03:56:53.8161615Z 	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:93)
2020-03-19T03:56:53.8163924Z 	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:148)
2020-03-19T03:56:53.8237414Z Makefile:65: recipe for target 'documents/itu-G.650.1-201803-v2.pdf' failed
2020-03-19T03:56:53.8240116Z make: *** [documents/itu-G.650.1-201803-v2.pdf] Error 255
```

**Comment by CAMOBAP795** [comment]
@Intelligent2013 let me know if I can help somehow

**Comment by Intelligent2013** [comment]
@CAMOBAP795  @ronaldtse I've added a namespace output for ITU xslt.
Document namespace: 'https://open.ribose.com/standards/itu' for itu-G.650.1-201803-v2.xml:
```
Preparing...
Input: FOP config (pdf_fonts_config.xml)
Input: XML (sources/itu-G.650.1-201803-v2.xml)
Input: XSL (/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/itu.recommendation.xsl)
Output: PDF (documents/itu-G.650.1-201803-v2.pdf)

Transforming...
file:/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/itu.recommendation.xsl; Line #63; Column #16; INFO: Document namespace: 'https://open.ribose.com/standards/itu'
```

**Comment by Intelligent2013** [comment]
I see two issues:
- xslt/un.recommendation.xsl' not found!
But real file has a name unece.recommendation.xsl

- for ubuntu workflow, there isn't error for document sources/iso-rice-en-sections.xml:
org.apache.fop.pdf.PDFConformanceException: PDF/UA-1 requires the title to be set.
And there isn't a debug information:
INFO: Document namespace: 'https://www.metanorma.org/ns/iso'
that shows for macos and debian workflows.
Looks like ubuntu workflow doesn't process 'core'.xsl into .xsl.

**Comment by Intelligent2013** [comment]
UNECE xml files changed! The root element 'unece-standard' changed to 'un-standard'. I have to change xslts.

**Comment by Intelligent2013** [comment]
@ronaldtse Just for information, in UN xml documents there aren't title element:
`<title type="title"...`

**Comment by Intelligent2013** [comment]
Further changes see in https://github.com/metanorma/mn-native-pdf/pull/78

**Pull request closed without merging**
