### PR TITLE
Add OGC module and build xslts

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by Intelligent2013** [comment]
@ronaldtse Something wrong in mn-samples-ogc repo:
```
Entering 'mn-samples-ogc'
From https://github.com/metanorma/mn-samples-ogc
* branch            gh-pages   -> FETCH_HEAD
fatal: refusing to merge unrelated histories
Stopping at 'mn-samples-ogc'; script returned non-zero status.

**Comment by Intelligent2013** [comment]
The source ogc-ogc-tcpnp.xml has an incorrect namespace 
```xmlns="https://standards.opengeospatial.org/document"```
instead of
```xmlns="https://www.metanorma.com/ns/ogc"```

**Comment by Intelligent2013** [comment]
@ronaldtse I've fixed OGC xslt issues.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Merging!

**Pull request merged**
