### PR TITLE
Makefile updated and yml removed temp

### PR DESCRIPTION
**Pull request by Intelligent2013**

### CODE REVIEW

**Comment by Intelligent2013** [comment]
@ronaldtse  Who is can solve this issue? Yesterday it processed successfully (https://github.com/metanorma/mn-native-pdf/runs/1056857057). 

```
2020-09-02T10:43:43.8830272Z bundle exec relaton concatenate \
2020-09-02T10:43:43.8830879Z   -t "mn2pdf samples" \
2020-09-02T10:43:43.8831102Z 	-g "Metanorma" \
2020-09-02T10:43:43.8831206Z 	documents documents.rxl
2020-09-02T10:43:45.3277185Z [relaton-bib] Series type is invalid: secondary
2020-09-02T10:43:45.3368994Z [relaton-bib] Series type is invalid: secondary
2020-09-02T10:43:45.3517365Z bundler: failed to load command: relaton (/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/relaton)
2020-09-02T10:43:45.3518072Z NoMethodError: undefined method `text' for nil:NilClass
2020-09-02T10:43:45.3518451Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:46:in `iho_group'
2020-09-02T10:43:45.3518826Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:31:in `block (2 levels) in fetch_editorialgroup'
2020-09-02T10:43:45.3519169Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
2020-09-02T10:43:45.3519496Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
2020-09-02T10:43:45.3519812Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
2020-09-02T10:43:45.3520116Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:30:in `map'
2020-09-02T10:43:45.3520470Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:30:in `block in fetch_editorialgroup'
2020-09-02T10:43:45.3520804Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
2020-09-02T10:43:45.3521119Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
2020-09-02T10:43:45.3521681Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
2020-09-02T10:43:45.3522160Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:29:in `map'
2020-09-02T10:43:45.3522492Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:29:in `fetch_editorialgroup'
2020-09-02T10:43:45.3522828Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.3.1/lib/relaton_bib/xml_parser.rb:55:in `item_data'
2020-09-02T10:43:45.3523149Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/xml_parser.rb:10:in `item_data'
2020-09-02T10:43:45.3523471Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.3.1/lib/relaton_bib/xml_parser.rb:11:in `from_xml'
2020-09-02T10:43:45.3523792Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.1/lib/relaton_iho/processor.rb:25:in `from_xml'
2020-09-02T10:43:45.3524111Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli.rb:38:in `parse_xml'
2020-09-02T10:43:45.3524424Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/bibdata.rb:39:in `from_xml'
2020-09-02T10:43:45.3524758Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:196:in `bibdata_instance'
2020-09-02T10:43:45.3525428Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:150:in `block in concatenate_files'
2020-09-02T10:43:45.3525914Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:142:in `each'
2020-09-02T10:43:45.3526228Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:142:in `reduce'
2020-09-02T10:43:45.3526670Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:142:in `concatenate_files'
2020-09-02T10:43:45.3527028Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
2020-09-02T10:43:45.3527590Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
2020-09-02T10:43:45.3527933Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
2020-09-02T10:43:45.3528251Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
2020-09-02T10:43:45.3528567Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli/command.rb:34:in `concatenate'
2020-09-02T10:43:45.3528867Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
2020-09-02T10:43:45.3529177Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
2020-09-02T10:43:45.3529826Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
2020-09-02T10:43:45.3530135Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
2020-09-02T10:43:45.3530725Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/lib/relaton/cli.rb:20:in `start'
2020-09-02T10:43:45.3531507Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-cli-1.3.0/exe/relaton:20:in `<top (required)>'
2020-09-02T10:43:45.3531976Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/relaton:23:in `load'
2020-09-02T10:43:45.3532286Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/relaton:23:in `<top (required)>'
2020-09-02T10:43:45.3576223Z make: *** [documents.rxl] Error 1
2020-09-02T10:43:45.3576713Z Makefile:293: recipe for target 'documents.rxl' failed
```

The differences are:
public_suffix 4.0.5 -> 4.0.6
relaton-iho 1.3.0 -> 1.3.1
relaton-w3c 1.3.1 -> 1.3.2

**Comment by ronaldtse** [comment]
@andrew2net could you have a look at this? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse we've changed the IHO model recently https://github.com/relaton/relaton-iho/issues/6#issuecomment-680161966
In this repo, there are IHO XML documents in the previous format. For example, mn-samples-iho/documents/c17.xml contains:
```yaml
<editorialgroup>
  <committee>ircc</committee>
  <workgroup>msdiwg</workgroup>
</editorialgroup>
```
these documents need to be updated

**Comment by Intelligent2013** [comment]
> these documents need to be updated

@andrew2net I've pushed a commit into mn-sample-iho (master branch), but there is an issue:
```
Running locally via bundle ...
nil versions are discouraged and will be deprecated in Rubygems 4
[relaton-iho] ("IHO S-100") fetching...
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: committee)
  /usr/local/bundle/gems/relaton-iho-1.3.0/lib/relaton_iho/editorial_group.rb:47:in `initialize'
  /usr/local/bundle/gems/relaton-iho-1.3.0/lib/relaton_iho/hash_converter.rb:28:in `new'
  /usr/local/bundle/gems/relaton-iho-1.3.0/lib/relaton_iho/hash_converter.rb:28:in `block in editorialgroup_hash_to_bib'
```
(https://github.com/metanorma/mn-samples-iho/runs/1066337877)

What I did wrong?

**Comment by andrew2net** [comment]
@Intelligent2013 first of all update relaton-iho to version 1.3.2. As I said before we've updated the IHO model recently, so the relaton-iho 1.3.0 can't parse the new data files.
Second, there are XML/RXL files in this repository that contain old editorialgroup elements. For example mn-samples-iho/documents/c17.xml and mn-samples-iho/documents/c17.rxl:
```yaml
...
  <editorialgroup>
    <committee>ircc</committee>
    <workgroup>msdiwg</workgroup>
  </editorialgroup>
...
```
which should be:
```yaml
...
  <editorialgroup>
    <committee>
      <abbreviation>IRCC</abbreviation>
      <workgroup>
        <abbreviation>MSDIWG</abbreviation>
      </workgroup>
    </committee>
  </editorialgroup>
...
```
I don't know where the files come from. Maby we just need to fetch these IHO documents again.

**Pull request closed without merging**
